apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-datanode
  namespace: hadoop
spec:
  maxReplicas: 3
  minReplicas: 1
  metrics:
  - resource:
      name: memory
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet 
    name: datanode 
