apiVersion: v1
kind: Service
metadata:
  name: datanode
  labels:
    app: datanode
  namespace: hadoop
spec:
  clusterIP: None
  ports:
    - name: "9864"
      port: 9864
      targetPort: 9864
    - name: "8042"
      port: 8042
      targetPort: 8042
  selector:
    app: datanode
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datanode
  namespace: hadoop
spec:
  selector:
    matchLabels:
      app: datanode
  serviceName: datanode
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: datanode
    spec:
      terminationGracePeriodSeconds: 0
      setHostnameAsFQDN: true
      containers:
        - imagePullPolicy: Never
          image: hadoop-datanode
          name: datanode
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 400m
              memory: 400Mi
          volumeMounts:
            - mountPath: /data/hdfs
              name: datanode-data
            - name: hadoop-conf
              mountPath: "/etc/hadoop/core-site.xml"
              subPath: core-site.xml
              readOnly: true
            - name: hadoop-conf
              mountPath: "/etc/hadoop/hdfs-site.xml"
              subPath: hdfs-site.xml
              readOnly: true
            - name: hadoop-conf
              mountPath: "/etc/hadoop/yarn-site.xml"
              subPath: yarn-site.xml
              readOnly: true
            - name: hadoop-conf
              mountPath: "/etc/hadoop/mapred-site.xml"
              subPath: mapred-site.xml
              readOnly: true
            - name: hadoop-conf
              mountPath: "/etc/hadoop/hadoop-env.sh"
              subPath: hadoop-env.sh
              readOnly: true
      volumes:
        - name: hadoop-conf
          configMap:
            name: hadoop-conf
  volumeClaimTemplates:
    - metadata:
        name: datanode-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 500Mi
