apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-conf
data:
  httpd.conf: |
    ServerRoot "/usr/local/apache2"

    LoadModule mpm_event_module modules/mod_mpm_event.so
    LoadModule authn_file_module modules/mod_authn_file.so
    LoadModule authn_core_module modules/mod_authn_core.so
    LoadModule authz_host_module modules/mod_authz_host.so
    LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
    LoadModule authz_user_module modules/mod_authz_user.so
    LoadModule authz_core_module modules/mod_authz_core.so
    LoadModule access_compat_module modules/mod_access_compat.so
    LoadModule auth_basic_module modules/mod_auth_basic.so
    LoadModule reqtimeout_module modules/mod_reqtimeout.so
    LoadModule request_module modules/mod_request.so
    LoadModule filter_module modules/mod_filter.so
    LoadModule proxy_html_module modules/mod_proxy_html.so
    LoadModule brotli_module modules/mod_brotli.so
    LoadModule mime_module modules/mod_mime.so
    LoadModule log_config_module modules/mod_log_config.so
    LoadModule env_module modules/mod_env.so
    LoadModule headers_module modules/mod_headers.so
    LoadModule setenvif_module modules/mod_setenvif.so
    LoadModule version_module modules/mod_version.so
    LoadModule remoteip_module modules/mod_remoteip.so
    LoadModule proxy_module modules/mod_proxy.so
    LoadModule proxy_http_module modules/mod_proxy_http.so
    LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so
    LoadModule ssl_module modules/mod_ssl.so
    LoadModule http2_module modules/mod_http2.so
    LoadModule proxy_http2_module modules/mod_proxy_http2.so
    LoadModule unixd_module modules/mod_unixd.so
    LoadModule status_module modules/mod_status.so
    LoadModule autoindex_module modules/mod_autoindex.so
    LoadModule vhost_alias_module modules/mod_vhost_alias.so
    LoadModule dir_module modules/mod_dir.so
    LoadModule alias_module modules/mod_alias.so
    LoadModule rewrite_module modules/mod_rewrite.so

    User www-data
    Group www-data

    ServerAdmin webmaster@localhost

    <Directory />
        AllowOverride none
        Require all denied
    </Directory>

    <IfModule dir_module>
        DirectoryIndex index.html
    </IfModule>

    <Files ".ht*">
        Require all denied
    </Files>

    ErrorLog /proc/self/fd/2

    LogLevel info

    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%h %l %u %t \"%r\" %>s %b" common

    CustomLog /proc/self/fd/1 common

    Include conf/extra/httpd-mpm.conf

    Listen 4040
    Listen 9864
    Listen 9870
    Listen 8042
    Listen 8089
    Listen 18080
    Listen 9999 
    Listen 9998

    <VirtualHost *:9864>
        ServerName datanode.hadoop.svc.127-0-0-1.nip.io
        ServerAlias *.datanode.hadoop.svc.127-0-0-1.nip.io

        RewriteEngine On
        RewriteCond %{HTTP_HOST} ([^.]+)
        RewriteRule ^/(.*) http://%1.datanode.hadoop.svc.127-0-0-1.nip.io:9864/$1 [P]

        <Proxy http://%1.datanode.hadoop.svc.127-0-0-1.nip.io:9864/$1>
            ProxySet disablereuse=on
        </Proxy>
    </VirtualHost>

    <VirtualHost *:8042>
        ServerName datanode.hadoop.svc.127-0-0-1.nip.io
        ServerAlias *.datanode.hadoop.svc.127-0-0-1.nip.io

        RewriteEngine On
        RewriteCond %{HTTP_HOST} ([^.]+)
        RewriteRule ^/(.*) http://%1.datanode.hadoop.svc.127-0-0-1.nip.io:8042/$1 [P]
        
        <Proxy http://%1.datanode.hadoop.svc.127-0-0-1.nip.io:8042/$1>
            ProxySet disablereuse=on
        </Proxy>
    </VirtualHost>

    <VirtualHost *:9870>
        ServerName namenode-0.namenode.hadoop.svc.127-0-0-1.nip.io
        ProxyPass        / http://namenode-0.namenode:9870/
        ProxyPassReverse / http://namenode-0.namenode:9870/
    </VirtualHost>

    <VirtualHost *:8089>
        ServerName resourcemanager-0.resourcemanager.hadoop.svc.127-0-0-1.nip.io
        ProxyPass        / http://resourcemanager-0.resourcemanager:8089/
        ProxyPassReverse / http://resourcemanager-0.resourcemanager:8089/
    </VirtualHost>

    <VirtualHost *:9999>
        ServerName namenode-0.namenode.hadoop.svc.127-0-0-1.nip.io
        ProxyPass        / http://namenode-0.namenode:9999/
        ProxyPassReverse / http://namenode-0.namenode:9999/
    </VirtualHost>

    <VirtualHost *:9998>
        ServerName resourcemanager-0.resourcemanager.hadoop.svc.127-0-0-1.nip.io
        ProxyPass        / http://resourcemanager-0.resourcemanager:9998/
        ProxyPassReverse / http://resourcemanager-0.resourcemanager:9998/
    </VirtualHost>

    <VirtualHost *:18080>
        ServerName spark.hadoop.svc.127-0-0-1.nip.io
        ProxyPass        / http://spark:18080/
        ProxyPassReverse / http://spark:18080/
    </VirtualHost>

    <VirtualHost *:4040>
        ServerName spark.hadoop.svc.127-0-0-1.nip.io
        ProxyPass        / http://spark:4040/
        ProxyPassReverse / http://spark:4040/
    </VirtualHost>
---
apiVersion: v1
kind: Pod
metadata:
  name: proxy
  namespace: hadoop
  labels:
    app: proxy
spec:
  initContainers:
    - name: init-namenode
      image: busybox
      command: ['sh', '-c', "until nslookup namenode-0.namenode.hadoop.svc.127-0-0-1.nip.io; do echo Waiting for namenode to come online; sleep 2; done"]
  containers:
    - name: httpd
      image: httpd
      volumeMounts:
        - name: apache-conf
          mountPath: /usr/local/apache2/conf/httpd.conf
          subPath: httpd.conf
          readOnly: true
  volumes:
    - name: apache-conf
      configMap:
        name: apache-conf
        items:
          - key: httpd.conf
            path: httpd.conf
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  type: NodePort
  ports:
    - name: "9864"
      port: 9864
      targetPort: 9864
      nodePort: 9864
    - name: "9870"
      port: 9870
      targetPort: 9870
      nodePort: 9870
    - name: "8020"
      port: 8020
      targetPort: 8020
      nodePort: 8020
    - name: "8042"
      port: 8042
      targetPort: 8042
      nodePort: 8042
    - name: "8089"
      port: 8089
      targetPort: 8089
      nodePort: 8089
    - name: "18080"
      port: 18080
      targetPort: 18080
      nodePort: 18080
    - name: "4040"
      port: 4040
      targetPort: 4040
      nodePort: 4040
    - name: "4041"
      port: 4041
      targetPort: 4041
      nodePort: 4041
    - name: "4042"
      port: 4042
      targetPort: 4042
      nodePort: 4042
    - name: "9999"
      port: 9999
      targetPort: 9999
      nodePort: 9999
    - name: "9998"
      port: 9998
      targetPort: 9998
      nodePort: 9998
  selector:
    app: proxy
