apiVersion: v1
kind: Service
metadata:
  name: resourcemanager
  labels:
    app: resourcemanager
  namespace: hadoop
spec:
  clusterIP: None
  ports:
    - name: "8089"
      port: 8089
      targetPort: 8089
    - name: "9998"
      port: 9998
      targetPort: 9998
  selector:
    app: resourcemanager
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resourcemanager
  namespace: hadoop
spec:
  selector:
    matchLabels:
      app: resourcemanager
  serviceName: resourcemanager
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: resourcemanager
    spec:
      terminationGracePeriodSeconds: 0
      setHostnameAsFQDN: true
      initContainers:
        - name: init-namenode
          image: busybox
          command: ['sh', '-c', "until nslookup namenode-0.namenode.hadoop.svc.127-0-0-1.nip.io; do echo Waiting for namenode to come online; sleep 2; done"]
      containers:
        - imagePullPolicy: Never
          image: hadoop-resourcemanager
          name: resourcemanager
          volumeMounts:
            - mountPath: /data/hdfs
              name: resourcemanager-data
            - name: hadoop-conf
              mountPath: "/etc/hadoop/core-site.xml"
              subPath: core-site.xml
              readOnly: true
            - name: hadoop-conf
              mountPath: "/etc/hadoop/hdfs-site.xml"
              subPath: hdfs-site.xml
              readOnly: true
            - name: hadoop-conf
              mountPath: "/etc/hadoop/yarn-site.xml"
              subPath: yarn-site.xml
              readOnly: true
            - name: hadoop-conf
              mountPath: "/etc/hadoop/mapred-site.xml"
              subPath: mapred-site.xml
              readOnly: true
            - name: hadoop-conf
              mountPath: "/etc/hadoop/hadoop-env.sh"
              subPath: hadoop-env.sh
              readOnly: true
      volumes:
        - name: hadoop-conf
          configMap:
            name: hadoop-conf
  volumeClaimTemplates:
    - metadata:
        name: resourcemanager-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 500Mi
